  
language: node_js
sudo: false
node_js:
- node
script:
 - npm run lint 
- npm run deploy
after_success:
 
 provider: firebase
  project: project12-a6cfa
  token: $FIREBASE_TOKEN
notifications:
 email: false